services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nerd_backlog_dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
