// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (nickname, email, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, nickname, email, hashed_password, inserted_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Nickname       string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Nickname, arg.Email, arg.HashedPassword)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRefreshTokenByAccountID = `-- name: DeleteRefreshTokenByAccountID :exec
DELETE FROM refresh_tokens
WHERE account_id = $1
`

func (q *Queries) DeleteRefreshTokenByAccountID(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByAccountID, accountID)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, nickname, email, hashed_password, inserted_at, updated_at, deleted_at FROM accounts
WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const storeRefreshToken = `-- name: StoreRefreshToken :exec
INSERT INTO refresh_tokens (token, account_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE SET token = EXCLUDED.token, expires_at = EXCLUDED.expires_at
`

type StoreRefreshTokenParams struct {
	Token     string
	AccountID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshToken, arg.Token, arg.AccountID, arg.ExpiresAt)
	return err
}
