// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, account_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string
	AccountID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.AccountID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSessionAccountID = `-- name: GetSessionAccountID :one
SELECT account_id FROM sessions
WHERE token = $1
  AND expires_at > now()
`

func (q *Queries) GetSessionAccountID(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionAccountID, token)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}
